//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocLab.App.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductValidationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocLab.App.Logic.Resources.ProductValidationMessages", typeof(ProductValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете изменить название товара на &apos;{0}&apos;, так как такое название уже занято.
        /// </summary>
        public static string ProductAliasIsAlreadyTakenFormat {
            get {
                return ResourceManager.GetString("ProductAliasIsAlreadyTakenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товарный бренд не найден по указанному идентификатору.
        /// </summary>
        public static string ProductBrandIsNotFoundByProvidedIdentifier {
            get {
                return ResourceManager.GetString("ProductBrandIsNotFoundByProvidedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден по указанному идентификатору.
        /// </summary>
        public static string ProductIsNotFoundByProvidedIdentifier {
            get {
                return ResourceManager.GetString("ProductIsNotFoundByProvidedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете изменить название товара на &apos;{0}&apos;, так как такое название уже занято.
        /// </summary>
        public static string ProductNameIsAlreadyTakenFormat {
            get {
                return ResourceManager.GetString("ProductNameIsAlreadyTakenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена товара не может быть меньше или равна нулю.
        /// </summary>
        public static string ProductPriceCantBeLessOrEqualThanZero {
            get {
                return ResourceManager.GetString("ProductPriceCantBeLessOrEqualThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар отредактирован.
        /// </summary>
        public static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с данным алиасом уже существует.
        /// </summary>
        public static string ProductWithProvidedAliasAlreadyExists {
            get {
                return ResourceManager.GetString("ProductWithProvidedAliasAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с данным названием уже существует.
        /// </summary>
        public static string ProductWithProvidedNameAlreadyExists {
            get {
                return ResourceManager.GetString("ProductWithProvidedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не имеете права редактировать этот товар, так как вы не являетесь продавцом в магазине, к которому этот товар принадлежит.
        /// </summary>
        public static string YouCantEditThisProductBecauseYouAreNotASellerInThisShop {
            get {
                return ResourceManager.GetString("YouCantEditThisProductBecauseYouAreNotASellerInThisShop", resourceCulture);
            }
        }
    }
}
