//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocLab.App.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShopValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopValidationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocLab.App.Logic.Resources.ShopValidationMessages", typeof(ShopValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин уже удален.
        /// </summary>
        public static string ShopAlreadyDeleted {
            get {
                return ResourceManager.GetString("ShopAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин создан.
        /// </summary>
        public static string ShopCreated {
            get {
                return ResourceManager.GetString("ShopCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин удален.
        /// </summary>
        public static string ShopDeleted {
            get {
                return ResourceManager.GetString("ShopDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание магазина не может быть пустым.
        /// </summary>
        public static string ShopDescriptionCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ShopDescriptionCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин не найден по указанному идентификатору.
        /// </summary>
        public static string ShopIsNotFoundByProvidedIdentifier {
            get {
                return ResourceManager.GetString("ShopIsNotFoundByProvidedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название магазина не может быть пустым.
        /// </summary>
        public static string ShopNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ShopNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В магазине еще есть товары.
        /// </summary>
        public static string ShopStillHasProducts {
            get {
                return ResourceManager.GetString("ShopStillHasProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин не найден.
        /// </summary>
        public static string ShoptNotFound {
            get {
                return ResourceManager.GetString("ShoptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин отредактирован.
        /// </summary>
        public static string ShopUpdated {
            get {
                return ResourceManager.GetString("ShopUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазин с данным названием уже существует.
        /// </summary>
        public static string ShopWithProvidedNameAlreadyExists {
            get {
                return ResourceManager.GetString("ShopWithProvidedNameAlreadyExists", resourceCulture);
            }
        }
    }
}
