/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

interface CrocoTypeDescription { 
    Name?: string;
    readonly TypeName?: string;
    readonly FullTypeName?: string;
    readonly DisplayName?: string;
    IsNullable?: boolean;
    IsEnumerable?: boolean;
    IsEnumeration?: boolean;
    IsClass?: boolean;
    EnumeratedType?: CrocoTypeDescription;
    EnumValues?: Array<CrocoEnumTypeDescription>;
    Properties?: Array<CrocoTypeDescription>;
    Descriptions?: Array<string>;
    readonly JsonExample?: string;
}
