/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact:
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
interface CrocoTypeDescription {
    PropertyDisplayName?: string;
    PropertyName?: string;
    readonly TypeName?: string;
    readonly FullTypeName?: string;
    readonly TypeDisplayName?: string;
    IsNullable?: boolean;
    IsEnumerable?: boolean;
    IsEnumeration?: boolean;
    IsClass?: boolean;
    EnumeratedType?: CrocoTypeDescription;
    EnumValues?: Array<CrocoEnumTypeDescription>;
    Properties?: Array<CrocoTypeDescription>;
    Description: string;
    Descriptions?: Array<string>;
    readonly JsonExample?: string;
}
